# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05890a2c5a7ff040b3c70eebab947a540e97b106332ca76a029e4a9cfa912728a23c4c4acfb5dfda8e40d6f2951c8147d6c13371c98763f447805e8ebfcde1fe

test:
  secret_key_base: 1965b67127dbfeb0117da5779828f5b53090917da2ccd7d808169036a7cde8140709da871836a1c36ae03f26cf33d1e5010065a4eedce02095db42efe474d4df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
